# Tensor Flow 2.0 :A quick tour

**TensorFlow 2.0 GPU version Install**

In [1]:
!python -m venv tensorflow-quick-env

In [2]:
!tensorflow-quick-env\Scripts\python -m pip install tensorflow==2.21.0

  Using cached packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
  Using cached typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
  Using cached charset_normalizer-3.4.9-cp313-cp313-win_amd64.whl.metadata (42 kB)
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
  Using cached certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
  Using cached wheel-0.47.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
  Using cached pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 2.4/351.2 MB 11.


[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: c:\Users\anand\OneDrive\Desktop\DL\DeepLearning\imageSegmentation\tensorflow-quick-env\Scripts\python.exe -m pip install --upgrade pip


In [3]:
!tensorflow-quick-env\Scripts\python -m pip install ipykernel
!tensorflow-quick-env\Scripts\python -m ipykernel install --user --name=tensorflow-quick-env

  Using cached ipykernel-7.3.0-py3-none-any.whl.metadata (4.5 kB)
  Using cached comm-0.2.3-py3-none-any.whl.metadata (3.7 kB)
  Using cached debugpy-1.8.21-cp313-cp313-win_amd64.whl.metadata (1.5 kB)
  Using cached ipython-9.16.1-py3-none-any.whl.metadata (4.6 kB)
  Using cached jupyter_client-8.9.1-py3-none-any.whl.metadata (8.5 kB)
  Using cached jupyter_core-5.9.1-py3-none-any.whl.metadata (1.5 kB)
  Using cached matplotlib_inline-0.2.2-py3-none-any.whl.metadata (2.4 kB)
  Using cached nest_asyncio2-1.7.2-py3-none-any.whl.metadata (6.3 kB)
  Using cached psutil-7.2.2-cp37-abi3-win_amd64.whl.metadata (22 kB)
  Using cached pyzmq-27.1.0-cp312-abi3-win_amd64.whl.metadata (6.0 kB)
  Using cached tornado-6.5.8-cp39-abi3-win_amd64.whl.metadata (2.9 kB)
  Using cached traitlets-5.16.1-py3-none-any.whl.metadata (10 kB)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
  Using cached ipython_pygments_lexers-1.1.1-py3-none-any.whl.metadata (1.1 kB)
  Using cached jedi-0.20.


[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: c:\Users\anand\OneDrive\Desktop\DL\DeepLearning\imageSegmentation\tensorflow-quick-env\Scripts\python.exe -m pip install --upgrade pip


Installed kernelspec tensorflow-quick-env in C:\Users\anand\AppData\Roaming\jupyter\kernels\tensorflow-quick-env


*1. Constant Tensor*

In [3]:
import numpy as np           # NumPy is a Python library used for working with arrays
import tensorflow as tf      #TensorFlow is a Python library for fast numerical computing created and released by Google

print(tf.__version__)
i = tf . constant ( 1 ) # tf.int32 type constant
l = tf . constant ( 1 , dtype = tf . int64 ) # tf.int64 type constant
f = tf . constant ( 1.23 ) #tf.float32 type constant
d = tf . constant ( 3.14 , dtype = tf . double ) # tf.double type constant
s = tf . constant ( "hello world" ) # tf.string type constant
b = tf . constant ( True ) #tf.bool type constant

#Tensor Output
print(i)
print(l)
print(f)
print(d)
print(s)
print(b)

#Numpy Output
print(i.numpy())

print ( tf . int64 == np . int64 )
print ( tf . bool == np . bool_)
print ( tf . double == np . float64 )
print ( tf . string == np . str_)

2.20.0
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1.23, shape=(), dtype=float32)
tf.Tensor(3.14, shape=(), dtype=float64)
tf.Tensor(b'hello world', shape=(), dtype=string)
tf.Tensor(True, shape=(), dtype=bool)
1
True
True
True
True


2.Scalars are tensors with rank = 0,

arrays are with rank = 1,

matrix are with rank = 2 ....

In [5]:
scalar = tf . constant ( True ) #A scalar is a rank 0 tensor
print(scalar)
print ( tf . rank ( scalar ))
print ( scalar . numpy (). ndim ) # tf.rank equals to the ndim function in numpy


tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor(0, shape=(), dtype=int32)
0


In [4]:
vector = tf . constant ([ 1.0 , 2.0 , 3.0 , 4.0 ]) #A vector is a rank 1 tensor
print(vector)
print ( tf . rank ( vector ))
print ( np . ndim ( vector . numpy ()))
print ( np . ndim ( vector))

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)
tf.Tensor(1, shape=(), dtype=int32)
1
1


In [7]:
matrix = tf . constant ([[ 1.0 , 2.0 ],[ 3.0 , 4.0 ]]) #A matrix is ​​a rank 2 tensor
print(matrix)
print ( tf . rank ( matrix ))
print ( np . ndim ( matrix ))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(2, shape=(), dtype=int32)
2


In [8]:
#A rank 3 tensor has three dimensions (a 3D array)

tensor3 = tf . constant ([[[ 1.0 , 2.0 ],[ 3.0 , 4.0 ]],[[ 5.0 , 6.0 ],[ 7.0 , 8.0 ]]]) # A rank 3 tensor
print ( tensor3 )
print ( tf . rank ( tensor3 ))
print ( np . ndim( tensor3 ))

tf.Tensor(
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]], shape=(2, 2, 2), dtype=float32)
tf.Tensor(3, shape=(), dtype=int32)
3


In [9]:
#A rank 4 tensor has four dimensions (a 4D array)

tensor4 = tf . constant ([[[[ 1.0 , 1.0 ],[ 2.0 , 2.0 ]],[[ 3.0 , 3.0 ],[ 4.0 , 4.0 ]]],
                         [[[ 5.0 , 5.0 ],[ 6.0 , 6.0 ]],[[ 7.0 , 7.0 ],[ 8.0 , 8.0 ]]]]) # A rank 4 tensor
print ( tensor4 )
print ( tf . rank ( tensor4 ))

tf.Tensor(
[[[[1. 1.]
   [2. 2.]]

  [[3. 3.]
   [4. 4.]]]


 [[[5. 5.]
   [6. 6.]]

  [[7. 7.]
   [8. 8.]]]], shape=(2, 2, 2, 2), dtype=float32)
tf.Tensor(4, shape=(), dtype=int32)


**3. Variable**

In [10]:
x=tf.Variable(451, tf.int16)
print(x)
print(x.numpy())
y=tf.Variable(551, tf.int16)
print(y.numpy())
print(x.numpy()+y.numpy())

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=451>
451
551
1002


In [11]:
# The value of a variable is changeable through re-assigning methods such as assign, assign_add, etc.
v = tf . Variable ([ 1.0 , 2.0 ], name = "v" )
print ( v )
print ( id ( v ))
v . assign_add ([ 1.0 , 1.0 ])
print ( v )
print ( id ( v ))

<tf.Variable 'v:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
133457059160976
<tf.Variable 'v:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>
133457059160976


**4.TensorFlow Arithematic**

In [12]:
# The value of a constant is NOT changeable. Re-assignment creates a new space in the memory.
c = tf . constant ([ 1.0 , 2.0 ])
print ( c )
print ( id ( c ))
c = c + tf . constant ([ 1.0 , 1.0 ])
print ( c )
print ( id ( c ))

tf.Tensor([1. 2.], shape=(2,), dtype=float32)
133459585939600
tf.Tensor([2. 3.], shape=(2,), dtype=float32)
133457060756560




**Making tensors by tf.zeros and tf.ones**

In [13]:
# Making a tensor filled with zeros. shape=[rows, columns]
tensor = tf.zeros(shape=[3, 4], dtype=tf.int32)
print(('Tensor full of zeros as int32, 3 rows and 4 columns:\n{0}').format(
    tensor.numpy()
))

# Making a tensor filled with zeros with data type of float32
tensor = tf.ones(shape=[5, 3], dtype=tf.float32)
print(('\nTensor full of ones as float32, 5 rows and 3 columns:\n{0}').format(
    tensor.numpy()
))

Tensor full of zeros as int32, 3 rows and 4 columns:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Tensor full of ones as float32, 5 rows and 3 columns:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# The linear algebra operations


1.   Transpose tensor
2. Matrix Multiplication
3. Element-wise multiplication
4. Identity Matrix
5. Determinant
6. Dot Product






In [14]:
#Transpose Tensor
# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

A = tf.transpose(A)

print(('The transposed matrix A:\n{0}').format(
    A
))

The transposed matrix A:
[[3 1]
 [7 9]]


In [15]:
#Matrix Multiplication
# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

# Some vector v
v = tf.constant([[5],
                 [2]])

# Matrix multiplication of A.v^T
Av = tf.matmul(A, v)

print(('Matrix Multiplication of A and v results in a new Tensor:\n{0}').format(
    Av
))

Matrix Multiplication of A and v results in a new Tensor:
[[29]
 [23]]


In [16]:
# Element-wise multiplication
Av = tf.multiply(A, v)

print(('Element-wise multiplication of A and v results in a new Tensor:\n{0}').format(
    Av
))

Element-wise multiplication of A and v results in a new Tensor:
[[15 35]
 [ 2 18]]


In [17]:
# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9],
                 [2, 5]])

# Get number of dimensions
rows, columns = A.shape
print(('Get rows and columns in tensor A:\n{0} rows\n{1} columns').format(
    rows, columns
))

# Making identity matrix
A_identity = tf.eye(num_rows = rows,
                    num_columns = columns,
                    dtype = tf.int32)
print(('\nThe identity matrix of A:\n{0}').format(
    A_identity.numpy()
))

Get rows and columns in tensor A:
3 rows
2 columns

The identity matrix of A:
[[1 0]
 [0 1]
 [0 0]]


In [18]:
#Determinant
# Reusing Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

# Determinant must be: half, float32, float64, complex64, complex128
# Thus, we cast A to the data type float32
A = tf.dtypes.cast(A, tf.float32)

# Finding the determinant of A
det_A = tf.linalg.det(A)

print(('The determinant of A:\n{0}').format(
    det_A
))

The determinant of A:
20.0


In [19]:
#Dot Product
# Defining a 3x3 matrix
A = tf.constant([[32, 83, 5],
                 [17, 23, 10],
                 [75, 39, 52]])

# Defining another 3x3 matrix
B = tf.constant([[28, 57, 20],
                 [91, 10, 95],
                 [37, 13, 45]])

# Finding the dot product
dot_AB = tf.tensordot(a=A, b=B, axes=1).numpy()

print(('Dot product of A.B^T results in a new Tensor:\n{0}').format(
    dot_AB
))

# Which is the same as matrix multiplication in this instance (axes=1)
# Matrix multiplication of A and B
AB = tf.matmul(A, B)

print(('\nMatrix Multiplication of A.B^T results in a new Tensor:\n{0}').format(
    AB
))

Dot product of A.B^T results in a new Tensor:
[[8634 2719 8750]
 [2939 1329 2975]
 [7573 5341 7545]]

Matrix Multiplication of A.B^T results in a new Tensor:
[[8634 2719 8750]
 [2939 1329 2975]
 [7573 5341 7545]]


You update the value of a Variable by using the methods .assign(value), or .assign_add(increment) or .assign_sub(decrement):

In [20]:
initial_value = tf.random.normal(shape=(2, 2))
a = tf.Variable(initial_value)
print(a)

new_value = tf.random.normal(shape=(2, 2))
a.assign(new_value)
for i in range(2):
    for j in range(2):
      assert a[i, j] == new_value[i, j]
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.69221145,  0.2916774 ],
       [-1.0906085 ,  0.954843  ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.15342028, -1.4997005 ],
       [ 0.22270302,  0.79452384]], dtype=float32)>


Tensor Reshaping

In [21]:
# Create a 1D tensor
tensor = tf.constant([1, 2, 3, 4, 5, 6])

# Reshape into a 2x3 matrix
reshaped_tensor = tf.reshape(tensor, [2, 3])

print(reshaped_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


# Calculate the Derivative Using the Gradient Tape

$f(x) = a\times{x^2} + b \times x + c$

In [22]:
import tensorflow as tf
import numpy as np

# Calculate the derivative of f(x) = a*x**2 + b*x + c

x = tf . Variable ( 0.0 , name = "x" , dtype = tf . float32 )
a = tf . constant ( 1.0 )
b = tf . constant ( -2.0 )
c = tf . constant ( 1.0 )

with tf . GradientTape () as tape :
  y = a * tf . pow ( x , 2 ) + b * x + c


dy_dx = tape . gradient ( y , x )
print ( dy_dx )


tf.Tensor(-2.0, shape=(), dtype=float32)
